// <auto-generated />
namespace Arthesanatus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ecluir_Tab_FotoReceitas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ecluir_Tab_FotoReceitas));
        
        string IMigrationMetadata.Id
        {
            get { return "202105060450489_Ecluir_Tab_FotoReceitas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
