// <auto-generated />
namespace Arthesanatus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlteracaoBD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlteracaoBD));
        
        string IMigrationMetadata.Id
        {
            get { return "202104080148372_AlteracaoBD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
